### ISSUE TITLE
Deploy to heroku

### ISSUE THREAD

**Issue by exitmusic** [exitmusic/math-o-magic#6]
The sooner the better.

**Comment by exitmusic** [comment]
Heroku error (same as running locally using "foreman start"):

```
2012-07-24T04:04:20+00:00 heroku[web.1]: Starting process with command `node server.js`
2012-07-24T04:04:23+00:00 app[web.1]: info: socket.io started
2012-07-24T04:04:23+00:00 app[web.1]: Starting cluster with 1 workers in undefined mode
2012-07-24T04:04:23+00:00 app[web.1]: `kill -s SIGUSR2 2` to force cluster reload
2012-07-24T04:04:23+00:00 app[web.1]: Go to: http://localhost:80/
2012-07-24T04:04:23+00:00 app[web.1]: 
2012-07-24T04:04:23+00:00 app[web.1]: events.js:66
2012-07-24T04:04:23+00:00 app[web.1]:         throw arguments[1]; // Unhandled 'error' event
2012-07-24T04:04:23+00:00 app[web.1]:                        ^
2012-07-24T04:04:23+00:00 app[web.1]:     at errnoException (net.js:776:11)
2012-07-24T04:04:23+00:00 app[web.1]: Error: listen EACCES
2012-07-24T04:04:23+00:00 app[web.1]:     at process.startup.processNextTick.process._tickCallback (node.js:244:9)
2012-07-24T04:04:23+00:00 app[web.1]:     at Server._listen2.self._handle.onconnection (net.js:899:28)
2012-07-24T04:04:24+00:00 heroku[web.1]: Process exited with status 1
2012-07-24T04:04:24+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by exitmusic** [comment]
Fixed the issue above by changing server.js:
Old:

```
require('derby').run(__dirname + '/lib/server')
```

New:

```
require('derby').run(__dirname + '/lib/server', process.env.PORT || 3000)
```

**Comment by exitmusic** [comment]
The solution above fixed the issue locally when using 'foreman' to start the app, but not remotely on heroku. Since I'm dropping Derby from this app, this should no longer be an issue.

**Comment by exitmusic** [comment]
This is now running on nodejitsu. Will look into deploying on Heroku again using this configuration:
https://devcenter.heroku.com/articles/using-socket-io-with-node-js-on-heroku
